/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sgev.view;

import com.sgev.dao.ProdutoDAO;
import com.sgev.model.Produto;

/**
 *
 * @author Miratech
 */
public class telaVendas extends javax.swing.JFrame {

    /**
     * Creates new form telaVendas
     */
    public telaVendas() {
        initComponents();
        this.setTitle("SGEV - Módulo de Vendas");
    this.setExtendedState(MAXIMIZED_BOTH); // Maximiza ao abrir
    this.setLocationRelativeTo(null);      // Centraliza caso o usuário minimize
    
    iniciarRelogio();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        cadastroMenuV = new javax.swing.JPopupMenu();
        itemMenuProdutosV = new javax.swing.JMenuItem();
        itemMenuCLientesV = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCadastroV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClientesV = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPesquisarProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResumoCompras = new javax.swing.JTable();
        btnFinalizarCompra = new javax.swing.JButton();
        txtHora = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        btnEmitirCupom = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        itemMenuProdutosV.setText("Produtos");
        itemMenuProdutosV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProdutosVActionPerformed(evt);
            }
        });
        cadastroMenuV.add(itemMenuProdutosV);

        itemMenuCLientesV.setText("Clientes");
        itemMenuCLientesV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCLientesVActionPerformed(evt);
            }
        });
        cadastroMenuV.add(itemMenuCLientesV);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon.focusedBackground"));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setAutoscrolls(true);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCadastroV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro.png"))); // NOI18N
        btnCadastroV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(153, 153, 153)));
        btnCadastroV.setContentAreaFilled(false);
        btnCadastroV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastroV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cadastro");

        btnClientesV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        btnClientesV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(153, 153, 153)));
        btnClientesV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesVActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastroV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClientesV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnClientesV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4))
            .addComponent(btnCadastroV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("VENDAS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BEM - VINDO");

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("SGEV");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel5)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel5)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode-scan.png"))); // NOI18N

        txtPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarProdutoActionPerformed(evt);
            }
        });
        txtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarProdutoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel8.setText("Pesquisar produto");

        tabelaResumoCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaResumoCompras.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tabelaResumoCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "QUANTIDADE", "PREÇO", "VALIDADE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResumoCompras.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaResumoCompras.setColumnSelectionAllowed(true);
        tabelaResumoCompras.setRowHeight(25);
        jScrollPane2.setViewportView(tabelaResumoCompras);
        tabelaResumoCompras.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnFinalizarCompra.setBackground(new java.awt.Color(153, 204, 255));
        btnFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrinho-de-compras.png"))); // NOI18N
        btnFinalizarCompra.setText("Finalizar");
        btnFinalizarCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        txtHora.setBackground(new java.awt.Color(51, 51, 255));
        txtHora.setForeground(new java.awt.Color(255, 255, 0));
        txtHora.setToolTipText("");
        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total R$");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText("0,00");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout txtHoraLayout = new javax.swing.GroupLayout(txtHora);
        txtHora.setLayout(txtHoraLayout);
        txtHoraLayout.setHorizontalGroup(
            txtHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtHoraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        txtHoraLayout.setVerticalGroup(
            txtHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal)
                    .addGroup(txtHoraLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblHora)))
                .addContainerGap())
        );

        btnEmitirCupom.setBackground(new java.awt.Color(153, 204, 255));
        btnEmitirCupom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEmitirCupom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comprovante.png"))); // NOI18N
        btnEmitirCupom.setText("Emitir Cupom");
        btnEmitirCupom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmitirCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirCupomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesquisarProduto)
                                .addGap(17, 17, 17))
                            .addComponent(txtCodigoBarras)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEmitirCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmitirCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmitirCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirCupomActionPerformed
        // 1. Verificar se há produtos na lista
    if (tabelaResumoCompras.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Não há produtos para emitir o cupom!");
        return;
    }

    // 2. Montar o corpo do cupom (estilo cupom fiscal)
    StringBuilder cupom = new StringBuilder();
    cupom.append("          SGEV - SISTEMA DE VENDAS          \n");
    cupom.append("--------------------------------------------\n");
    cupom.append("ITEM     QTD      VALOR UN.      TOTAL \n");

    for (int i = 0; i < tabelaResumoCompras.getRowCount(); i++) {
        String nome = tabelaResumoCompras.getValueAt(i, 0).toString();
        String qtd = tabelaResumoCompras.getValueAt(i, 1).toString();
        String preco = tabelaResumoCompras.getValueAt(i, 2).toString();
        cupom.append(String.format("%-10s %-8s %-12s %-10s\n", nome, qtd, preco, preco));
    }

    cupom.append("--------------------------------------------\n");
    cupom.append("VALOR TOTAL: R$ ").append(txtTotal.getText()).append("\n");
    cupom.append("--------------------------------------------\n");
    cupom.append("      OBRIGADO PELA PREFERENCIA!      \n");

    // 3. Criar o arquivo e abrir no Bloco de Notas
    try {
        java.io.File arquivo = new java.io.File("cupom_venda.txt");
        java.io.PrintWriter gravar = new java.io.PrintWriter(arquivo);
        gravar.print(cupom.toString());
        gravar.close();

        // Comando para abrir o arquivo automaticamente no Windows
        java.awt.Desktop.getDesktop().open(arquivo);
        
    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gerar cupom: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnEmitirCupomActionPerformed

    private void txtPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoActionPerformed
       
    }//GEN-LAST:event_txtPesquisarProdutoActionPerformed

    private void btnCadastroVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroVActionPerformed
        cadastroMenuV.show(btnCadastroV, 0, btnCadastroV.getHeight());
    }//GEN-LAST:event_btnCadastroVActionPerformed

    private void itemMenuProdutosVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProdutosVActionPerformed
        cadastroProdutos cp = new cadastroProdutos();
    cp.setLocationRelativeTo(null);
    cp.setVisible(true);

    }//GEN-LAST:event_itemMenuProdutosVActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void itemMenuCLientesVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCLientesVActionPerformed
        // 1. Cria a nova tela
    cadastroClientes telaCli = new cadastroClientes();
    
    // 2. Faz ela abrir em tela cheia (como você pediu para as vendas)
    //telaCli.setExtendedState(MAXIMIZED_BOTH);
    
    // 3. Torna a tela visível
    telaCli.setVisible(true);
    
   
    }//GEN-LAST:event_itemMenuCLientesVActionPerformed

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
   String codigoDigitado = txtCodigoBarras.getText().trim();
    
    if (!codigoDigitado.isEmpty()) {
        com.sgev.dao.ProdutoDAO dao = new com.sgev.dao.ProdutoDAO();
        com.sgev.model.Produto p = dao.buscarPorCodigo(codigoDigitado);
        
        if (p != null) {
            String qtdString = javax.swing.JOptionPane.showInputDialog(this, 
                    "Digite a quantidade para " + p.getNome() + ":", "Quantidade", 
                    javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (qtdString != null && !qtdString.isEmpty()) {
                try {
                    int qtd = Integer.parseInt(qtdString);
                    double precoUnitario = p.getPrecoVenda().doubleValue();
                    
                    // O Subtotal será usado apenas para a função somarTotalTabela()
                    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaResumoCompras.getModel();
                    
                    // CORREÇÃO DA ORDEM DAS COLUNAS:
                    modelo.addRow(new Object[]{
                        p.getNome(),       // Coluna 0: ITEM
                        qtd,               // Coluna 1: QUANTIDADE
                        precoUnitario,     // Coluna 2: PREÇO (Unitário)
                        p.getValidade()    // Coluna 3: VALIDADE (Agora o subtotal não vai mais para cá)
                    });

                    txtCodigoBarras.setText("");
                    txtCodigoBarras.requestFocus();
                    somarTotalTabela(); // Esta função precisa calcular (Preço * Quantidade)
                    
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Erro: Digite um número inteiro para a quantidade.");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        }
    }
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void somarTotalTabela() {
    double totalGeral = 0;
    for (int i = 0; i < tabelaResumoCompras.getRowCount(); i++) {
        // Pega a quantidade da linha (Coluna 1)
        int qtd = Integer.parseInt(tabelaResumoCompras.getValueAt(i, 1).toString());
        
        // Pega o preço unitário da linha (Coluna 2)
        double precoUnitario = Double.parseDouble(tabelaResumoCompras.getValueAt(i, 2).toString());
        
        // Multiplica e soma ao total
        totalGeral += (qtd * precoUnitario);
    }
    
    // Atualiza o campo de texto do total
    txtTotal.setText(String.format("%.2f", totalGeral));
}
    
    private void iniciarRelogio() {
    // Cria um Timer que executa a cada 1000 milissegundos (1 segundo)
    javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            // Pega a hora atual do sistema
            java.util.Date agora = new java.util.Date();
            // Define o formato: Horas:Minutos:Segundos
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss");
            // Atualiza o texto do JLabel
            lblHora.setText(sdf.format(agora));
        }
    });
    timer.start(); // Inicia o relógio
}
    
    
    
    
    
    
    
    
    
    
    private void btnClientesVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesVActionPerformed
      buscaEditCliente telaBusca = new buscaEditCliente();
    telaBusca.setLocationRelativeTo(null);
    telaBusca.setVisible(true);
    
  
    }//GEN-LAST:event_btnClientesVActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // 1. Verificar se a tabela está vazia antes de finalizar
    if (tabelaResumoCompras.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "A lista de compras está vazia!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Criar uma String para acumular os nomes dos produtos
    StringBuilder listaProdutos = new StringBuilder();
    listaProdutos.append("--- PRODUTOS COMPRADOS ---\n");

    for (int i = 0; i < tabelaResumoCompras.getRowCount(); i++) {
        String nomeProd = tabelaResumoCompras.getValueAt(i, 0).toString(); // Coluna ITEM
        String qtd = tabelaResumoCompras.getValueAt(i, 1).toString();      // Coluna QUANTIDADE
        listaProdutos.append(qtd).append("x - ").append(nomeProd).append("\n");
    }

    // 3. Adicionar o valor total ao final da mensagem
    listaProdutos.append("----------------------------\n");
    listaProdutos.append("TOTAL DA COMPRA: R$ ").append(txtTotal.getText());

    // 4. Exibir o Pop-up com o resumo completo
    javax.swing.JOptionPane.showMessageDialog(this, listaProdutos.toString(), "Venda Finalizada", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // 5. Limpar a tabela e o total para a próxima venda
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaResumoCompras.getModel();
    modelo.setRowCount(0);
    txtTotal.setText("0,00");
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void txtPesquisarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoKeyReleased
        // 1. Pega o termo digitado
    String nomeBusca = txtPesquisarProduto.getText().trim();
    
    // 2. Executa a busca no DAO apenas se o campo não estiver vazio
    if (!nomeBusca.isEmpty()) {
        com.sgev.dao.ProdutoDAO dao = new com.sgev.dao.ProdutoDAO();
        java.util.List<com.sgev.model.Produto> lista = dao.buscarPorNome(nomeBusca);
        
        // 3. Verifica se o usuário apertou ENTER e se encontrou algum produto
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !lista.isEmpty()) {
            // Pega o primeiro produto da lista encontrada
            com.sgev.model.Produto p = lista.get(0);
            
            // Adiciona na sua tabela de vendas
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaResumoCompras.getModel();
            modelo.addRow(new Object[]{
                p.getNome(), 
                1, 
                p.getPrecoVenda().doubleValue(), 
                p.getValidade()
            });
            
            // Limpa o campo e atualiza o total
            txtPesquisarProduto.setText("");
            somarTotalTabela(); // Sua função de soma
        }
    }
    }//GEN-LAST:event_txtPesquisarProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new telaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroV;
    private javax.swing.JButton btnClientesV;
    private javax.swing.JButton btnEmitirCupom;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JPopupMenu cadastroMenuV;
    private javax.swing.JMenuItem itemMenuCLientesV;
    private javax.swing.JMenuItem itemMenuProdutosV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTable tabelaResumoCompras;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JPanel txtHora;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

   
    }
